stages:
  - "Release"

Releasing Docker Image:
  image: shibme/docker-buildx
  services:
    - docker:dind
  stage: "Release"
  variables:
    BUILD_PLATFORMS: "linux/amd64,linux/arm64/v8"
    DOCKER_HOST: tcp://docker:2375/
    ECR_PUBLIC_REGISTRY: "public.ecr.aws"
    DOCKERHUB_IMAGE: "$CI_PROJECT_PATH"
    ECR_PUBLIC_IMAGE: "$ECR_PUBLIC_REGISTRY/$CI_PROJECT_PATH"
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_PUBLIC_REGISTRY
    - docker buildx create --driver docker-container --use
    - docker buildx inspect --bootstrap
  script:
    - update-binfmts --enable
    - docker buildx build --platform $BUILD_PLATFORMS -t "$CI_REGISTRY_IMAGE" --push .
    - docker buildx build --platform $BUILD_PLATFORMS -t "$DOCKERHUB_IMAGE" --push .
    - docker buildx build --platform $BUILD_PLATFORMS -t "$ECR_PUBLIC_IMAGE" --push .
  after_script:
    - docker logout
    - docker logout $ECR_PUBLIC_REGISTRY
    - docker logout $CI_REGISTRY
  only:
    - main